## These two functions allow a matrix to be stored as an object, inside which
## its value and inverse value can be stored.

## This function creates the object. In this the matrix value can be set or 
## retrieved using the x$set() or x$get() functions. The inv functions are also
## stored in this object. x$getinv returns the matrix inverse that is cached,
## once generated by the cacheSolve function. The $setinv function is
## used by the cacheSolve function to store the inverse value in the cache. 
## The $set function ensures that if the stored matrix value is changed, the 
## cached inverse value is reset to null. $get and $getinv allow these values
## to be retrieved

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinv <- function(inv1) i <<- inv1
        getinv <- function() i
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## cacheSolve retrieves the inverse of a matrix stored in a matrix object 
## created by makeCacheMatrix or it generates the inverse of this matrix and stores
## this value in the cache for future recall

cacheSolve <- function(x, ...) {
        i <- x$getinv()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinv(i)
        i
}
